name: 'Milestone Review Action'
description: 'Checks if the given Milestone exists and all the issues are closed'
inputs:
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    default: ${{github.token}}
    required: true
  milestone-title:
    description: 'The milestone to check'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
